"""
MongoDB document schemas for DeepCue.

Each TypedDict maps directly to a MongoDB collection document.
These are used for type checking and IDE auto-complete only —
MongoDB does not enforce them at the database level.

Collections:
  - interview_sessions  → InterviewSession
  - emotion_frames      → EmotionFrame
  - transcript_segments → TranscriptSegment
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional, TypedDict


class EmotionScores(TypedDict):
    """Fusion pipeline output: confidence per emotion class (must sum to 1.0)."""

    neutral: float
    confident: float
    anxious: float
    happy: float
    sad: float
    angry: float
    surprised: float
    uncertain: float


class EmotionFrame(TypedDict):
    """
    One fused inference result, written to MongoDB by the fusion Celery task.
    Keyed by session_id + frame_index for ordered reconstruction of the timeline.
    """

    session_id: str
    timestamp: float          # Unix epoch seconds (UTC)
    frame_index: int          # Monotonically increasing within the session
    video_score: float        # Raw output from VideoEmotionPipeline (0.0–1.0)
    audio_score: float        # Raw output from AudioEmotionPipeline (0.0–1.0)
    text_score: float         # Raw output from TextEmotionPipeline (0.0–1.0)
    fusion_scores: EmotionScores
    dominant_emotion: str     # Key with highest value in fusion_scores


class TranscriptSegment(TypedDict):
    """
    One Whisper transcription chunk, written to MongoDB by the text Celery task.
    Hebrew text stored as-is (RTL rendering handled by the PDF reporting layer).
    """

    session_id: str
    timestamp: float          # Start time of this audio chunk (Unix epoch, UTC)
    segment_index: int        # Monotonically increasing within the session
    text: str                 # Hebrew transcript text from Whisper
    language: str             # Detected language code, e.g. "he"
    duration_seconds: float   # Length of the audio chunk that produced this segment


class InterviewSession(TypedDict):
    """
    Root session document, created on `session_start` WebSocket message
    and finalised on `session_end`.
    """

    session_id: str           # UUID4 string, generated by the Channels consumer
    created_at: datetime
    updated_at: datetime
    status: str               # "active" | "completed" | "error"
    candidate_name: str
    duration_seconds: float   # Populated on session_end
    frame_count: int          # Total EmotionFrames written during the session
    dominant_emotion: str     # Most frequent dominant_emotion across all frames
    report_url: Optional[str] # MongoDB GridFS download URL; None until report is generated
